name = "Logistics"
uuid = "e933307e-f964-4372-9340-e36d39c2f667"
authors = ["Yu-Chang YANG <yang.yc.allium@gmail.com>"]
version = "0.1.0"

[compat]
Aqua = "0.6"
julia = "1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
